import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "../components/theme-provider";
import { Navbar } from "../components/navbar";
import { Footer } from "../components/footer";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className="font-sans antialiased min-h-screen flex flex-col"
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* Global Background Images */}
          <div className="fixed inset-0 z-0 pointer-events-none">
            <Image src="/hero_bg_islamic.png" alt="Geometric Background" fill className="object-cover opacity-5 dark:opacity-10 mix-blend-luminosity" priority />
          </div>
          <div className="fixed inset-0 z-0 pointer-events-none">
            <Image src="/ambient_glow.png" alt="Ambient Glow" fill className="object-cover opacity-[0.15] dark:opacity-20 mix-blend-plus-lighter" priority />
          </div>

          <div className="relative z-10 flex-1 flex flex-col min-h-screen">
            <Navbar />
            <main className="flex-1 flex flex-col">{children}</main>
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
